#!/bin/sh
set -eu
if [ "$(id -u)" -ne 0 ]; then exec sudo /opt/masspanel-updater/venv/bin/python /opt/masspanel-updater/current/masspanel-updater.py "$@"; fi
exec /opt/masspanel-updater/venv/bin/python /opt/masspanel-updater/current/masspanel-updater.py "$@"
