location = /masspanel-source {
    alias /usr/share/doc/masspanel/masspanel-source.html;
    default_type text/html;
}
location = /masspanel-corresponding-source.tar.gz {
    alias /usr/share/masspanel/source/masspanel-corresponding-source.tar.gz;
    default_type application/gzip;
    add_header Content-Disposition 'attachment; filename="masspanel-corresponding-source.tar.gz"';
}
location = /masspanel-open-source-license {
    alias /usr/share/doc/masspanel/LICENSE;
    default_type text/plain;
}
