clamav {
  action = "reject";
  message = "Virus detected";
  scan_mime_parts = true;
  scan_text_mime = false;
  scan_image_mime = false;
  max_size = 67108864;
  symbol = "CLAM_VIRUS";
  type = "clamav";
  servers = "127.0.0.1:3310";
  whitelist = "/etc/rspamd/antivirus.wl";
}
