import { useEffect, useMemo, useState } from 'react';
import { api, asArray } from '../legacy.jsx';
import '../firewall.css';

const EMPTY = { blocked:[], ignored:[], listeners:[], jails:[], fail2ban_banned:[], policy:{ bantime:3600, findtime:600, maxretry:5 } };

export default function FirewallPage({ session }) {
  const [data,setData] = useState(EMPTY), [query,setQuery] = useState(''), [selected,setSelected] = useState(null);
  const [policy,setPolicy] = useState(EMPTY.policy), [busy,setBusy] = useState(''), [error,setError] = useState('');
  async function load(){try{const next=await api('/firewall');const normalized={...EMPTY,...next,blocked:asArray(next?.blocked),ignored:asArray(next?.ignored),listeners:asArray(next?.listeners),jails:asArray(next?.jails),fail2ban_banned:asArray(next?.fail2ban_banned)};setData(normalized);setPolicy(normalized.policy||EMPTY.policy);setError('');}catch(reason){setError(reason.message);}}
  useEffect(()=>{load();},[]);
  async function inspect(ip){setBusy(`inspect-${ip}`);setError('');try{setSelected(await api(`/firewall/ip/${encodeURIComponent(ip)}`));}catch(reason){setError(reason.message);}finally{setBusy('');}}
  async function addressAction(ip,action){setBusy(`${action}-${ip}`);setError('');try{if(action==='block')await api('/firewall/block',{method:'POST',csrf:session.csrf,body:JSON.stringify({ip})});if(action==='unblock')await api(`/firewall/block/${encodeURIComponent(ip)}`,{method:'DELETE',csrf:session.csrf});if(action==='ignore')await api('/firewall/ignore',{method:'POST',csrf:session.csrf,body:JSON.stringify({ip})});if(action==='unignore')await api(`/firewall/ignore/${encodeURIComponent(ip)}`,{method:'DELETE',csrf:session.csrf});await load();await inspect(ip);}catch(reason){setError(reason.message);}finally{setBusy('');}}
  async function submitSearch(event){event.preventDefault();if(query.trim())await inspect(query.trim());}
  async function savePolicy(event){event.preventDefault();setBusy('policy');setError('');try{await api('/firewall/policy',{method:'PUT',csrf:session.csrf,body:JSON.stringify(policy)});await load();}catch(reason){setError(reason.message);}finally{setBusy('');}}
  const addresses=useMemo(()=>{const map=new Map();asArray(data.blocked).forEach(ip=>map.set(ip,{ip,manual:true}));asArray(data.fail2ban_banned).forEach(ip=>map.set(ip,{...(map.get(ip)||{ip}),automatic:true}));asArray(data.ignored).forEach(ip=>map.set(ip,{...(map.get(ip)||{ip}),ignored:true}));const needle=query.trim().toLowerCase();return [...map.values()].filter(item=>!needle||item.ip.toLowerCase().includes(needle)).sort((a,b)=>a.ip.localeCompare(b.ip));},[data.blocked,data.fail2ban_banned,data.ignored,query]);
  const ports=useMemo(()=>asArray(data.listeners).filter((item,index,list)=>list.findIndex(other=>other?.port===item?.port&&other?.protocol===item?.protocol)===index),[data.listeners]);
  return <section className="firewall-page">
    <header className="firewall-hero"><div><h1>Firewall manager</h1><p>Search any IP, investigate blocks and control server protection from one place.</p></div><div className="firewall-engine"><span/><small>Protection engine</small><b>{data.engine||'nftables'} · {data.active?'active':'checking'}</b></div></header>
    {error?<div className="form-error">{error}</div>:null}
    <div className="firewall-metrics"><article><small>Manually blocked</small><b>{data.blocked.length}</b><span>persistent rules</span></article><article><small>Automatic blocks</small><b>{data.fail2ban_banned.length}</b><span>Fail2ban bans</span></article><article><small>Always allowed</small><b>{data.ignored.length}</b><span>trusted addresses</span></article><article><small>Trusted admin IP</small><b className="metric-ip">{data.trusted_ip||'Updating on login'}</b><span>protected from lockout</span></article></div>
    <section className="firewall-card firewall-address-center"><header><div><h2>IP address center</h2><p>Click an entry for details, or search any IPv4 or IPv6 address.</p></div><button className="secondary" onClick={load}>Refresh</button></header><form className="firewall-search" onSubmit={submitSearch}><input aria-label="Search IP address" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search or enter an IP address…"/><button className="primary" disabled={!query.trim()||!!busy}>Inspect IP</button></form><div className="firewall-address-layout"><div className="firewall-address-table"><div className="firewall-address-head"><span>IP address</span><span>Source</span><span>Status</span></div>{addresses.map(item=><button key={item.ip} className={selected?.ip===item.ip?'selected':''} onClick={()=>inspect(item.ip)}><code>{item.ip}</code><span>{item.manual?'Manual rule':item.automatic?'Fail2ban':'Allow list'}</span><strong className={item.ignored?'allowed':'blocked'}>{item.ignored?'Allowed':'Blocked'}</strong></button>)}{!addresses.length?<div className="empty">{query?'No saved address matches. Click Inspect IP to check it.':'No blocked or allowed addresses.'}</div>:null}</div><aside className="firewall-inspector">{selected?<><header><div><small>Selected address</small><h3>{selected.ip}</h3></div><button aria-label="Close IP details" onClick={()=>setSelected(null)}>×</button></header><div className="ip-state"><span className={selected.ignored?'allowed':selected.blocked||selected.fail2ban_jails?.length?'blocked':'neutral'}>{selected.ignored?'Always allowed':selected.blocked||selected.fail2ban_jails?.length?'Blocked':'No active rule'}</span><small>{selected.version}</small></div>{selected.fail2ban_jails?.length?<div className="ip-jails"><b>Fail2ban jails</b><span>{selected.fail2ban_jails.join(', ')}</span></div>:null}<div className="ip-actions">{!selected.blocked&&!selected.ignored?<button className="danger" disabled={!!busy} onClick={()=>addressAction(selected.ip,'block')}>Block IP</button>:null}{selected.blocked||selected.fail2ban_jails?.length?<button className="secondary" disabled={!!busy} onClick={()=>addressAction(selected.ip,'unblock')}>Unblock everywhere</button>:null}{!selected.ignored?<button className="secondary" disabled={!!busy} onClick={()=>addressAction(selected.ip,'ignore')}>Always allow</button>:<button className="secondary" disabled={!!busy} onClick={()=>addressAction(selected.ip,'unignore')}>Remove allow rule</button>}</div><div className="ip-history"><b>Recent firewall activity</b>{asArray(selected.history).map(item=><div key={item.id}><span>{item.action}</span><time>{item.created_at}</time></div>)}{!asArray(selected.history).length?<small>No recorded actions for this address.</small>:null}</div></>:<div className="empty">Select or inspect an IP to manage it.</div>}</aside></div></section>
    <div className="firewall-grid"><section className="firewall-card"><header><div><h2>Brute-force policy</h2><p>Configure global Fail2ban thresholds.</p></div><span className={data.fail2ban_active?'firewall-ok':'firewall-warn'}>{data.fail2ban_active?'Active':'Needs attention'}</span></header><form className="firewall-policy" onSubmit={savePolicy}><label>Failed attempts<input type="number" min="1" max="20" value={policy.maxretry} onChange={event=>setPolicy(current=>({...current,maxretry:Number(event.target.value)}))}/></label><label>Detection window (seconds)<input type="number" min="60" max="86400" value={policy.findtime} onChange={event=>setPolicy(current=>({...current,findtime:Number(event.target.value)}))}/></label><label>Block time (seconds)<input type="number" min="60" max="604800" value={policy.bantime} onChange={event=>setPolicy(current=>({...current,bantime:Number(event.target.value)}))}/></label><button className="primary" disabled={!!busy}>{busy==='policy'?'Applying…':'Save protection policy'}</button></form><div className="jail-list">{data.jails.map(jail=><div key={jail.name}><b>{jail.name}</b><span>{jail.banned} currently banned</span></div>)}</div></section><section className="firewall-card"><header><div><h2>Listening services</h2><p>Ports currently accepting TCP or UDP traffic.</p></div></header><div className="service-chips">{ports.map(item=><article key={`${item.protocol}-${item.port}`}><b>{item.port}/{item.protocol.toUpperCase()}</b><span>{item.process||'system service'}</span><small>{item.address}</small></article>)}</div></section></div>
  </section>;
}
