import { useEffect, useMemo, useState } from 'react';
import { api, asArray } from '../legacy.jsx';

export default function FirewallPage({ session }) {
  const [data,setData] = useState({blocked:[],ignored:[],listeners:[],jails:[],fail2ban_banned:[]});
  const [ip,setIp] = useState(''); const [ignoreIp,setIgnoreIp] = useState(''); const [busy,setBusy] = useState(''); const [error,setError] = useState('');
  async function load(){ try{const next=await api('/firewall');setData({...next,blocked:asArray(next?.blocked),ignored:asArray(next?.ignored),listeners:asArray(next?.listeners),jails:asArray(next?.jails),fail2ban_banned:asArray(next?.fail2ban_banned)});setError('');}catch(reason){setError(reason.message);} }
  useEffect(()=>{load();},[]);
  async function block(e){e.preventDefault();setBusy('block');setError('');try{await api('/firewall/block',{method:'POST',csrf:session.csrf,body:JSON.stringify({ip})});setIp('');await load();}catch(reason){setError(reason.message);}finally{setBusy('');}}
  async function unblock(address){setBusy(address);setError('');try{await api(`/firewall/block/${encodeURIComponent(address)}`,{method:'DELETE',csrf:session.csrf});await load();}catch(reason){setError(reason.message);}finally{setBusy('');}}
  async function ignore(e){e.preventDefault();setBusy('ignore');setError('');try{await api('/firewall/ignore',{method:'POST',csrf:session.csrf,body:JSON.stringify({ip:ignoreIp})});setIgnoreIp('');await load();}catch(reason){setError(reason.message);}finally{setBusy('');}}
  async function unignore(address){setBusy(`ignore-${address}`);setError('');try{await api(`/firewall/ignore/${encodeURIComponent(address)}`,{method:'DELETE',csrf:session.csrf});await load();}catch(reason){setError(reason.message);}finally{setBusy('');}}
  const ports=useMemo(()=>asArray(data.listeners).filter((item,index,list)=>list.findIndex(other=>other?.port===item?.port&&other?.protocol===item?.protocol)===index),[data.listeners]);
  return <section className="firewall-page">
    <header className="firewall-hero"><div><h1>Firewall manager</h1><p>Control server blocks, review exposed services and monitor brute-force protection.</p></div><div className="firewall-engine"><span/><small>Protection engine</small><b>{data.engine||'nftables'} · {data.active?'active':'checking'}</b></div></header>
    {error&&<div className="form-error">{error}</div>}
    <div className="firewall-metrics"><article><small>Manually blocked</small><b>{data.blocked?.length||0}</b><span>persistent nftables rules</span></article><article><small>Fail2ban blocks</small><b>{data.fail2ban_banned?.length||0}</b><span>automatic brute-force bans</span></article><article><small>Protected services</small><b>{data.jails?.length||0}</b><span>active Fail2ban jails</span></article><article><small>Trusted admin IP</small><b className="metric-ip">{data.trusted_ip||'Updating on login'}</b><span>never manually blocked</span></article></div>
    <div className="firewall-grid"><section className="firewall-card"><header><div><h2>Blocked addresses</h2><p>Immediately drop all traffic from an address.</p></div><button className="secondary" onClick={load}>Refresh</button></header><form className="block-form" onSubmit={block}><label><span>IPv4 or IPv6 address</span><input value={ip} onChange={e=>setIp(e.target.value)} placeholder="203.0.113.24" required/></label><button className="primary" disabled={!!busy}>{busy==='block'?'Blocking…':'Block address'}</button></form><div className="firewall-list">{asArray(data.blocked).map(address=><div key={address}><code>{address}</code><span>Manual block</span><button className="secondary" disabled={!!busy} onClick={()=>unblock(address)}>{busy===address?'Removing…':'Unblock'}</button></div>)}{!asArray(data.blocked).length&&<div className="empty">No manually blocked addresses.</div>}</div></section>
    <section className="firewall-card"><header><div><h2>Always allow / ignore</h2><p>Never block trusted addresses manually or through Fail2ban.</p></div></header><form className="block-form" onSubmit={ignore}><label><span>Trusted IPv4 or IPv6 address</span><input value={ignoreIp} onChange={e=>setIgnoreIp(e.target.value)} placeholder="198.51.100.10" required/></label><button className="primary" disabled={!!busy}>{busy==='ignore'?'Adding…':'Add to allow list'}</button></form><div className="firewall-list">{asArray(data.ignored).map(address=><div key={address}><code>{address}</code><span>Always allowed</span><button className="secondary" disabled={!!busy} onClick={()=>unignore(address)}>{busy===`ignore-${address}`?'Removing…':'Remove'}</button></div>)}{!asArray(data.ignored).length&&<div className="empty">No additional ignored addresses.</div>}</div></section></div>
    <div className="firewall-grid">
    <section className="firewall-card"><header><div><h2>Brute-force protection</h2><p>Fail2ban watches authentication logs and blocks repeated failures.</p></div><span className={data.fail2ban_active?'firewall-ok':'firewall-warn'}>{data.fail2ban_active?'Active':'Needs attention'}</span></header><div className="jail-list">{asArray(data.jails).map(jail=><div key={jail.name}><b>{jail.name}</b><span>{jail.banned} currently banned</span></div>)}{!asArray(data.jails).length&&<div className="empty">No active Fail2ban jails reported.</div>}</div></section></div>
    <section className="firewall-card"><header><div><h2>Listening services</h2><p>Ports currently accepting TCP or UDP traffic. Exposure can also depend on upstream firewalls.</p></div></header><div className="service-chips">{ports.map(item=><article key={`${item.protocol}-${item.port}`}><b>{item.port}/{item.protocol.toUpperCase()}</b><span>{item.process||'system service'}</span><small>{item.address}</small></article>)}</div></section>
  </section>;
}
