import React, { useEffect, useMemo, useState } from 'react';
import { api } from '../legacy.jsx';

const empty = { enabled: false, hostname: '', store_name: 'Hosting Store', currency: 'USD', contact_email: '', template_mode: 'default', custom_template: '', custom_css: '', custom_js: '' };
const tabs = ['setup', 'packages', 'orders', 'theme'];

function SectionHead({ title, description, children }) { return <header className="store-section-head"><div><h2>{title}</h2><p>{description}</p></div>{children}</header>; }
function StorePreview({ settings, products }) { const visible = products.filter((item) => item.enabled).slice(0, 3); return <div className="store-preview-browser"><div className="store-preview-bar"><i /><i /><i /><span>{settings.hostname || 'store.example.com'}</span></div><div className="store-preview-page"><header><b>{settings.store_name || 'Hosting Store'}</b><span>Plans&nbsp;&nbsp; Contact</span></header><main><h3>Hosting built for real work</h3><p>Fast, secure hosting with straightforward plans and real support.</p><div className="store-preview-plans">{visible.map((item) => <article className={item.featured ? 'featured' : ''} key={item.id}><b>{item.display_name}</b><strong>{settings.currency} {item.monthly_price}</strong><small>per month</small><button type="button">Request plan</button></article>)}{!visible.length && <div className="store-preview-empty">Publish a package to preview your plans.</div>}</div></main></div></div>; }

function ThemeEditor({ settings, setSettings, saveSettings, busy }) {
  const set = (key) => (event) => setSettings({ ...settings, [key]: event.target.value });
  return <form className="store-tab-panel store-theme-panel" onSubmit={saveSettings}>
    <SectionHead title="Theme" description="Build the public store with HTML, Jinja, CSS and JavaScript." />
    <div className="store-theme-options"><label className={settings.template_mode === 'default' ? 'selected' : ''}><input type="radio" checked={settings.template_mode === 'default'} onChange={() => setSettings({ ...settings, template_mode: 'default' })} /><b>MassPanel default</b><small>Responsive and automatically updated.</small></label><label className={settings.template_mode === 'custom' ? 'selected' : ''}><input type="radio" checked={settings.template_mode === 'custom'} onChange={() => setSettings({ ...settings, template_mode: 'custom' })} /><b>Custom HTML + Jinja</b><small>Full document control with live package data.</small></label></div>
    {settings.template_mode === 'custom' && <label>HTML and Jinja template<textarea className="store-code" value={settings.custom_template} onChange={set('custom_template')} placeholder={'<!doctype html>\n<h1>{{ store.store_name }}</h1>\n{% for product in packages %}\n  <h2>{{ product.display_name }}</h2>\n{% endfor %}'} /></label>}
    <label>Custom CSS<textarea className="store-code store-code-small" value={settings.custom_css} onChange={set('custom_css')} placeholder="/* Added automatically before </head> */" /></label>
    <label>Custom JavaScript<textarea className="store-code store-code-small" value={settings.custom_js} onChange={set('custom_js')} placeholder={'// Available automatically\nMassPanelStore.packages.forEach((plan) => console.log(plan.display_name));'} /></label>
    <div className="store-code-warning"><b>Custom code runs on your public store.</b><span>Only paste code you trust. Package and store data are available through the interfaces below.</span></div>
    <details className="store-data-reference"><summary>Package data and template reference</summary><div>
      <h3>Jinja template</h3><pre>{`{% for product in packages %}\n  {{ product.id }}\n  {{ product.display_name }}\n  {{ product.description }}\n  {{ product.monthly_price }}\n  {{ product.yearly_price }}\n  {{ product.domain_limit }}\n  {{ product.disk_mb }}\n  {{ product.bandwidth_mb }}\n  {{ product.database_limit }}\n  {{ product.mailbox_limit }}\n{% endfor %}`}</pre>
      <h3>JavaScript or JSON</h3><pre>{`const data = window.MassPanelStore;\ndata.packages.forEach((product) => {\n  console.log(product.display_name, product.monthly_price);\n});\n\nfetch('/data.json').then(r => r.json()).then(console.log);`}</pre>
      <h3>Order form</h3><pre>{`<form method="post" action="{{ storefront.order_url }}">\n  <input type="hidden" name="product_id" value="{{ product.id }}">\n  <input name="name" required>\n  <input type="email" name="email" required>\n  <select name="billing_cycle"><option value="monthly">Monthly</option></select>\n  <button>Request plan</button>\n</form>`}</pre>
      <p>Optional fields: <code>company</code>, <code>phone</code>, <code>domain</code>, and <code>notes</code>. The JSON endpoint returns enabled packages only.</p>
    </div></details>
    <div className="store-theme-footer"><label>Currency<input value={settings.currency} maxLength="3" onChange={(e) => setSettings({ ...settings, currency: e.target.value.toUpperCase() })} required /></label><button className="primary" disabled={!!busy}>{busy === 'settings' ? 'Saving…' : 'Save theme'}</button></div>
  </form>;
}

export default function StorePage({ session }) {
  const [data, setData] = useState({ settings: empty, packages: [], products: [], orders: [] });
  const [settings, setSettings] = useState(empty); const [tab, setTab] = useState('setup'); const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function load() { const next = await api('/store'); setData(next); setSettings({ ...empty, ...next.settings, enabled: !!next.settings.enabled }); }
  useEffect(() => { load().catch((x) => setError(x.message)); }, []);
  const published = useMemo(() => new Map(data.products.map((item) => [item.package_id, item])), [data.products]); const pending = data.orders.filter((order) => order.status === 'pending').length;
  function start(action) { setBusy(action); setMessage(''); setError(''); }
  async function saveSettings(event) { event.preventDefault(); start('settings'); try { await api('/store/settings', { method: 'PUT', csrf: session.csrf, body: JSON.stringify(settings) }); setMessage('Storefront changes published.'); await load(); } catch (x) { setError(x.message); } finally { setBusy(''); } }
  async function saveProduct(event, item) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); values.enabled = event.currentTarget.enabled.checked; values.featured = event.currentTarget.featured.checked; start(`product-${item.id}`); try { await api(`/store/products/${item.id}`, { method: 'PUT', csrf: session.csrf, body: JSON.stringify(values) }); setMessage(`${item.name} updated.`); await load(); } catch (x) { setError(x.message); } finally { setBusy(''); } }
  async function certificate() { start('certificate'); try { const result = await api('/store/certificate', { method: 'POST', csrf: session.csrf, body: JSON.stringify({ force: true }) }); setMessage(`TLS certificate ready for ${result.hostname}.`); } catch (x) { setError(x.message); } finally { setBusy(''); } }
  async function orderStatus(id, status) { start(`order-${id}`); try { await api(`/store/orders/${id}`, { method: 'PUT', csrf: session.csrf, body: JSON.stringify({ status }) }); await load(); } catch (x) { setError(x.message); } finally { setBusy(''); } }
  return <div className="store-admin"><section className="store-admin-title"><div><h1>Storefront</h1><p>Configure, publish and manage hosting plan requests.</p></div><div className="store-admin-actions"><span className={settings.enabled ? 'store-live' : 'store-offline'}><i />{settings.enabled ? 'Store is live' : 'Store is offline'}</span><a className="secondary" href="/api/store/preview" target="_blank" rel="noreferrer">Preview ↗</a>{settings.enabled && settings.hostname && <a className="secondary" href={`https://${settings.hostname}`} target="_blank" rel="noreferrer">View live store ↗</a>}</div></section>
    <nav className="store-tabs" aria-label="Storefront sections">{tabs.map((item) => <button type="button" key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item[0].toUpperCase() + item.slice(1)}{item === 'orders' && pending > 0 && <span>{pending}</span>}</button>)}</nav>{error && <div className="form-error">{error}</div>}{message && <div className="notice">{message}</div>}
    {tab === 'setup' && <form className="store-workspace" onSubmit={saveSettings}><section className="store-editor-pane"><SectionHead title="Store setup" description="Brand identity, address and availability." /><label>Store name<input value={settings.store_name} onChange={(e) => setSettings({ ...settings, store_name: e.target.value })} required /></label><label>Sales email<input type="email" value={settings.contact_email} placeholder="sales@example.com" onChange={(e) => setSettings({ ...settings, contact_email: e.target.value })} /></label><div className="store-domain-block"><h3>Store address</h3><label>Domain or subdomain<input value={settings.hostname} placeholder="store.example.com" onChange={(e) => setSettings({ ...settings, hostname: e.target.value })} /></label><div className="store-readiness"><span><i className={settings.hostname ? 'ok' : ''} />Domain configured</span><span><i className={settings.enabled ? 'ok' : ''} />Store enabled</span></div><button type="button" className="secondary" disabled={!settings.enabled || busy === 'certificate'} onClick={certificate}>{busy === 'certificate' ? 'Issuing certificate…' : 'Regenerate TLS certificate'}</button></div><div className="store-publish-row"><div><b>Publish storefront</b><small>Visitors can access the store at the configured address.</small></div><label className="store-switch"><input type="checkbox" checked={settings.enabled} onChange={(e) => setSettings({ ...settings, enabled: e.target.checked })} /><span /></label></div><button className="primary store-save" disabled={!!busy}>{busy === 'settings' ? 'Publishing…' : 'Save changes'}</button></section><aside className="store-preview-pane"><SectionHead title="Live storefront preview" description="Updates as you edit." /><StorePreview settings={settings} products={data.products} /></aside></form>}
    {tab === 'packages' && <section className="store-tab-panel"><SectionHead title="Store packages" description="Publish existing hosting packages with customer-facing names and prices." /><div className="store-package-table">{data.packages.map((item) => { const current = published.get(item.id) || {}; return <form key={item.id} onSubmit={(e) => saveProduct(e, item)}><div className="store-plan-summary"><span className="store-plan-icon">{item.name[0]?.toUpperCase()}</span><div><b>{item.name}</b><small>{item.domain_limit} domains · {item.disk_mb} MB storage · {item.mailbox_limit} mailboxes · {item.database_limit} databases</small></div></div><div className="store-plan-flags"><label><input name="enabled" type="checkbox" defaultChecked={!!current.enabled} /> Published</label><label><input name="featured" type="checkbox" defaultChecked={!!current.featured} /> Featured</label></div><div className="store-package-fields"><label>Public name<input name="display_name" defaultValue={current.display_name || item.name} /></label><label>Monthly<input name="monthly_price" type="number" min="0" step="0.01" defaultValue={current.monthly_price || '0.00'} /></label><label>Yearly<input name="yearly_price" type="number" min="0" step="0.01" defaultValue={current.yearly_price || '0.00'} /></label><label>Order<input name="sort_order" type="number" defaultValue={current.sort_order || 0} /></label></div><label>Description<textarea name="description" defaultValue={current.description || ''} maxLength="1000" placeholder="A concise explanation of who this plan is for." /></label><footer><button className="primary" disabled={!!busy}>{busy === `product-${item.id}` ? 'Saving…' : 'Save package'}</button></footer></form>; })}{!data.packages.length && <div className="store-empty-state"><b>No packages to publish</b><p>Create a hosting package in Hosting tools, then return here to add pricing.</p></div>}</div></section>}
    {tab === 'orders' && <section className="store-tab-panel"><SectionHead title="Orders" description="Review customer requests and move them through your manual sales process." /><div className="store-orders-table"><header><span>Order</span><span>Customer</span><span>Package</span><span>Requested domain</span><span>Status</span></header>{data.orders.map((order) => <article key={order.id}><div><b>{order.order_number}</b><small>{order.created_at}</small></div><div><b>{order.customer_name}</b><a href={`mailto:${order.customer_email}`}>{order.customer_email}</a></div><div><b>{order.package_name}</b><small>{order.billing_cycle}</small></div><div>{order.requested_domain || '—'}</div><select aria-label={`Status for ${order.order_number}`} value={order.status} disabled={busy === `order-${order.id}`} onChange={(e) => orderStatus(order.id, e.target.value)}>{['pending','contacted','approved','rejected','completed'].map((status) => <option key={status}>{status}</option>)}</select></article>)}{!data.orders.length && <div className="store-empty-state"><b>No orders yet</b><p>New storefront requests will appear here.</p></div>}</div></section>}
    {tab === 'theme' && <ThemeEditor settings={settings} setSettings={setSettings} saveSettings={saveSettings} busy={busy} />}
  </div>;
}
