import React, { useEffect, useState } from 'react';
import { api, asArray } from '../legacy.jsx';

const labels = {available:'Update available',current:'Up to date',complete:'Update installed',downloading:'Downloading',backing_up:'Creating backup',installing:'Installing',verifying:'Running checks',failed:'Update failed',rolled_back:'Rolled back',rolling_back:'Rolling back'};

export default function UpdatesPage({session}) {
  const [data,setData]=useState(null), [busy,setBusy]=useState(''), [error,setError]=useState(''), [notice,setNotice]=useState('');
  const load=async(refresh=false)=>{setBusy(refresh?'check':'load');setError('');try{setData(await api(`/system/updates${refresh?'?refresh=1':''}`));}catch(x){setError(x.message);}finally{setBusy('');}};
  useEffect(()=>{load(true);},[]);
  const act=async(action,snapshot='')=>{if(action==='rollback'&&!window.confirm(`Roll back to ${snapshot}? The panel will briefly restart.`))return;setBusy(action);setError('');try{await api(`/system/updates/${action}`,{method:'POST',csrf:session.csrf,body:JSON.stringify({snapshot})});setNotice(action==='apply'?'Update started. The panel may be unavailable briefly; this page will reconnect automatically.':'Rollback started. The panel will restart shortly.');setTimeout(()=>load(false),8000);}catch(x){setError(x.message);setBusy('');}};
  const status=data?.status||{}, manifest=data?.manifest||{}, available=status.available_version&&status.available_version!==status.current_version;
  return <><header className="page-header"><div><h1>Updates</h1><p>Install signed MassPanel releases, review their contents and recover from a previous snapshot.</p></div><button className="secondary" disabled={!!busy} onClick={()=>load(true)}>{busy==='check'?'Checking…':'Check for updates'}</button></header><div className="updates-workspace">{error&&<div className="form-error">{error}</div>}{notice&&<div className="notice">{notice}</div>}<section className="update-hero"><div><small>Installed version</small><strong>{status.current_version||'Unknown'}</strong><span className={`update-state state-${status.state||'unknown'}`}>{labels[status.state]||status.state||'Not checked'}</span></div><div><small>Available version</small><strong>{status.available_version||manifest.version||'Check now'}</strong><span>{status.message||'Use Check for updates to contact the release server.'}</span></div><button className="primary" disabled={!available||!!busy} onClick={()=>act('apply')}>{busy==='apply'?'Starting…':available?'Install update':'Up to date'}</button></section><div className="updates-columns"><section className="settings-panel"><header><div><h2>What this update includes</h2><p>Contents are read from the cryptographically signed release manifest.</p></div></header><div className="release-list">{asArray(manifest.components).map(item=><article key={item.name||item}><span>✓</span><div><b>{item.name||item}</b>{item.description&&<p>{item.description}</p>}</div></article>)}{!asArray(manifest.components).length&&<div className="empty">No newer release is available. Release details will appear here after a check.</div>}</div></section><section className="settings-panel"><header><div><h2>Compatibility lock</h2><p>MassPanel application dependencies are pinned without blocking Ubuntu security updates.</p></div></header><dl className="update-facts"><div><dt>Python packages</dt><dd>{data?.package_lock?.python_requirements||'Exact versions pinned'}</dd></div><div><dt>System packages</dt><dd>{data?.package_lock?.system_policy||'Recorded and compatibility checked'}</dd></div><div><dt>Update channel</dt><dd>{manifest.channel||'beta'}</dd></div><div><dt>Signature</dt><dd>{manifest.signature?.algorithm==='ed25519'?'Ed25519 verified':'Verified by updater'}</dd></div></dl></section></div><section className="settings-panel update-history"><header><div><h2>Recovery snapshots</h2><p>A snapshot is created automatically before every update.</p></div></header>{asArray(data?.backups).map(item=><div className="update-snapshot" key={item.name}><div><b>{item.name}</b><small>{item.created_at} · {(item.size/1048576).toFixed(1)} MB</small></div><button className="secondary" disabled={!!busy} onClick={()=>act('rollback',item.name)}>Roll back</button></div>)}{!asArray(data?.backups).length&&<div className="empty">No recovery snapshots yet.</div>}</section></div></>;
}
